### ISSUE TITLE
error when two set skins in sequence

### ISSUE THREAD

**Issue by CrazyD00** [NagasonicDev/Skonic#3]
Hey,

When I set skin with a different URL or identical, 2 successive NPC .
The first one is good and the second one makes a mistake.

Is there a minimum waiting time? Which one?
Sincerely

[message.txt](https://github.com/user-attachments/files/17964119/message.txt)

**Comment by NagasonicDev** [comment]
Hi @CrazyD00,
Looking at the error, this is not a problem with the addon, but because of the URL. Error 429 means that the client (Skonic in this case) has sent to many requests in a given amount of time. This time is decided by the url (api.mineskin.com), and is not something I can fix directly. But, I should be able to change the syntax to allow an array of citizens to be changed at once.

**Comment by NagasonicDev** [comment]
As of now, this is set to be included in the next update.
